In [2]:
# 사용자로부터 나이를 입력받는다. 유효 범위는 (1~150)
# 성인(20세 이상) 이면 요금이 15000원 이고, 청소년이면 8000원(12~19세), 그 외에는 3000원을 받는다.
# 이 로직을 반복하고, 영업을 종료 시킬 수 있는 입력을 받을 수 있다.
# 영업이 종료되면, 결산을 한다.
# "성인", "청소년", "그 외" 컬럼을 출력하고, 아래에 각 컬럼에 해당되는 사람이 몇명이 왔는지, 그 아래에 각 컬럼의 유형이 총 얼마를 냈는지 적고, 마지막으로 총 벌어들인 요금을 출력한다.

adult_count = 0
teen_count = 0
other_count = 0
adult_total = 0
teen_total = 0
other_total = 0
total = 0
count = 0

while True:
  count += 1
  # 나이 입력 받기
  age = input("나이를 입력하세요: ")
  # 입력값 검증
  if not age.isnumeric():
      print("숫자를 입력하세요.")
      continue

  age = int(age)

  if age < 1 or age > 150:
      print("1~150 사이의 나이를 입력하세요.")
      continue

  # 나이에 따른 가격 책정
  if age >= 20:
      adult_count += 1
      adult_total += 15000
  elif age >= 12:
      teen_count += 1
      teen_total += 8000
  else:
      other_count += 1
      other_total += 3000

  # 종료 입력 받기
  if count %5 == 0 :
    finish = input("영업을 종료하시겠습니까? (y/n): ")
    if finish == 'y':
        break

print("{:^10} {:^10} {:^10}".format("성인", "청소년", "그 외"))
print("{:^10} {:^10} {:^10}".format(adult_count, teen_count, other_count))
print("{:^10,} {:^10,} {:^10,}".format(adult_total, teen_total, other_total))
total = adult_total + teen_total + other_total
print("총 벌어들인 요금: {:,}원".format(total))

나이를 입력하세요: 1
나이를 입력하세요: 13
나이를 입력하세요: 99
나이를 입력하세요: 0
1~150 사이의 나이를 입력하세요.
나이를 입력하세요: 150
영업을 종료하시겠습니까? (y/n): y
    성인        청소년        그 외
    2          1          1
  30,000     8,000      3,000
총 벌어들인 요금: 41,000원

In [4]:
import random
list1 = [random.randrange(100) for i in range(10)]

def calc(list) :
  # 최대값 구하기
  max_val = max(list)
  # 최소값 구하기
  min_val = min(list)
  # 평균값 구하기
  avg_val = sum(list) / len(list)
  # 합계 구하기
  sum_val = sum(list)

  # 결과 출력
  print("최대값:", max_val)
  print("최소값:", min_val)
  print("평균값:", avg_val)
  print("합계:", sum_val)

print(list1)
calc(list1)

[26, 75, 3, 1, 40, 20, 55, 79, 83, 61]
최대값: 83
최소값: 1
평균값: 44.3
합계: 443